### ISSUE TITLE
报错：Server disconnected without sending a response.

### ISSUE THREAD

**Issue by Agnes4m** [Reversedeer/nonebot_plugin_dog#1]
指令  `舔狗日记`
返回  `Server disconnected without sending a response.`
版本v0.1.9

**Comment by Reversedeer** [comment]
还有更具体的报错吗，发日志看看

**Comment by Agnes4m** [comment]
nb端是没有报错。。。我刚刚换了一个python3.9环境的服务器是成功了，但是在python3.10上报这个错...也许缺什么库了...

**Comment by Agnes4m** [comment]
```

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.10/site-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/usr/local/lib/python3.10/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 576, in run
    server.run()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.10/site-packages/nonebot/message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/site-packages/nonebot/internal/matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/site-packages/nonebot/internal/matcher.py", line 688, in simple_run
    await handler(
  File "/usr/local/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/ubuntu/bot/game/nb2/./src/plugins/nonebot_plugin_dog/__init__.py", line 33, in dog
    response = await client.get("https://api.juncikeji.xyz/api/tgrj.php")
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1729, in get
    return await self.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1506, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1593, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1621, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1658, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1695, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: Server disconnected without sending a response.
```

**Comment by Reversedeer** [comment]
因为开发环境在3.9上，3.10没测试

**Comment by Reversedeer** [comment]
你可以卸载httpx，然后pip install httpx试试

**Comment by Agnes4m** [comment]
不行，同样的报错，httpx==0.22.0-0.23.3都失败

**Comment by Reversedeer** [comment]
我明天再看看，不过不建议使用py3.10

**Comment by Agnes4m** [comment]
还有一个问题，回复的消息后面多一行空格

**Comment by Reversedeer** [comment]
> 还有一个问题，回复的消息后面多一行空格

在下个版本会修复

**Comment by Reversedeer** [comment]
> nb端是没有报错。。。我刚换了一个python3.9环境的服务器成功了，但是在python3.10上报这个也有错...许缺什么库了...

应该是你的网络原因造成的，不是插件的问题
在py3.10上测试没有问题

**Comment by Reversedeer** [comment]
更新了，具体看readme

**Comment by Reversedeer** [comment]
> 更新了，具体看readme

抱歉了，少发了一个包最新v0.2.3

**Comment by Reversedeer** [comment]
@Umamusume-Agnes-Digital 试试看有没有问题

**Comment by Agnes4m** [comment]
没毛病
